@startuml
'https://plantuml.com/class-diagram

interface Shape {
    +draw(): void
}

class Circle implements Shape {
    +draw(): void
}

class Rectangle implements Shape {
    +draw(): void
}

class Square implements Shape {
    +draw(): void
}

class ShapeMaker {
    -circle: Shape
    -rectangle: Shape
    -square: Shape

    +ShapeMaker()
    +drawCircle(): void
    +drawRectangle(): void
    +drawSquare(): void
}

Square *-- ShapeMaker
Circle *-- ShapeMaker
Rectangle *-- ShapeMaker

@enduml